### PR TITLE
Update common.json

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Devnol** [comment]
you could just commit to themeswitcher directly but sure

**Comment by ghost** [comment]
> 
> 
> you could just commit to themeswitcher directly but sure

it wouldn't let me

**Comment by Devnol** [comment]
uh ok

**Comment by cfanoulis** [comment]
(they arent an org member - if you're a hackropolis member and i've forgotten to add you please send a nudge over at leaders@hackropolis.club thanks)

**Pull request merged**
